//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mobile()
        {
            this.Shop_Mobiles = new HashSet<Shop_Mobiles>();
        }
    
        public int Id { get; set; }
        public string MobileName { get; set; }
        public string About { get; set; }
        public Nullable<double> Price { get; set; }
        public string SIM { get; set; }
        public Nullable<bool> DualSIM { get; set; }
        public string Proccessor { get; set; }
        public string Dimensions { get; set; }
        public string PhoneWeight { get; set; }
        public string PackageContent { get; set; }
        public string Size { get; set; }
        public string Resolution { get; set; }
        public string ScreenType { get; set; }
        public string DataTransfer { get; set; }
        public string Network2G { get; set; }
        public string Network3G { get; set; }
        public string Network4G { get; set; }
        public string FrontCameraChar { get; set; }
        public string BackCameraChar { get; set; }
        public string USB { get; set; }
        public string WiFi { get; set; }
        public string Bluetooth { get; set; }
        public Nullable<bool> NFC { get; set; }
        public Nullable<bool> GPS { get; set; }
        public string PhoneMessages { get; set; }
        public string AdditionalDescription { get; set; }
        public string Video { get; set; }
        public Nullable<bool> Touch { get; set; }
        public Nullable<bool> FMRadio { get; set; }
        public Nullable<bool> Port35mm { get; set; }
        public Nullable<bool> HDVoice { get; set; }
        public Nullable<int> BatteryId { get; set; }
        public Nullable<int> FrontCameraId { get; set; }
        public Nullable<int> BackCameraId { get; set; }
        public Nullable<int> InternMemoryId { get; set; }
        public Nullable<int> ExternMemoryId { get; set; }
        public Nullable<int> RamId { get; set; }
        public Nullable<int> OsId { get; set; }
    
        public virtual Battery Battery { get; set; }
        public virtual Camera Camera { get; set; }
        public virtual Camera Camera1 { get; set; }
        public virtual Memory Memory { get; set; }
        public virtual Memory Memory1 { get; set; }
        public virtual OperativeSystem OperativeSystem { get; set; }
        public virtual RAM RAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_Mobiles> Shop_Mobiles { get; set; }
    }
}
