//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mobile()
        {
            this.Shop_Mobiles = new HashSet<Shop_Mobiles>();
        }
    
        public int Id { get; set; }
        public string About { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> PlatformId { get; set; }
        public Nullable<int> ScreenId { get; set; }
        public Nullable<int> CameraId { get; set; }
        public Nullable<int> MemoryId { get; set; }
        public Nullable<int> SoundId { get; set; }
        public Nullable<int> CommunicationId { get; set; }
        public Nullable<int> BatteryId { get; set; }
        public Nullable<int> CharacteristicsId { get; set; }
        public Nullable<int> AdditionalId { get; set; }
        public Nullable<int> PackageContentId { get; set; }
    
        public virtual Additional Additional { get; set; }
        public virtual Battery Battery { get; set; }
        public virtual Camera Camera { get; set; }
        public virtual Characteristic Characteristic { get; set; }
        public virtual Communication Communication { get; set; }
        public virtual Memory Memory { get; set; }
        public virtual PackageContent PackageContent { get; set; }
        public virtual PhonePlatform PhonePlatform { get; set; }
        public virtual Screen Screen { get; set; }
        public virtual Sound Sound { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_Mobiles> Shop_Mobiles { get; set; }
    }
}
